nandhas:
  enableNotification: true
server:
  port: 8080
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  data:
    mongodb:
      uri: mongodb://mongo/auth
  application:
    name: auth-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
facebook:
  client:
    clientId: 233668646673605
    clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me
github:
  client:
    clientId: bd1c0a783ccdd1c9b9e4
    clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user
google:
  client:
    clientId: 662755376164-cs6a2qual95s5sjjgb97djeuerriln1p.apps.googleusercontent.com
    clientSecret: OVGohjL-WND8hRp4pta3_MvU
    accessTokenUri: https://www.googleapis.com/oauth2/v3/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: profile
  resource:
    userInfoUri: https://www.googleapis.com/userinfo/v2/me
    preferTokenInfo: false
twitter:
  client:
    clientId: oXJIDGVdB0PDnMICDwKckyzKm
    clientSecret: Z4BpN51kNsb2wbEfzDXm40v38W3I2P1u4H6fvfM6HQraVfry5j
    accessTokenUri: https://api.twitter.com/oauth/access_token
    userAuthorizationUri: https://api.twitter.com/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri:  https://api.twitter.com/1.1/users/show.json
linkedin:
  client:
    clientId: 81azzvwsu7bon8
    clientSecret: 9zHzgRdyJPYSIdH4
    accessTokenUri: https://www.linkedin.com/oauth/v2/accessToken
    userAuthorizationUri: https://www.linkedin.com/oauth/v2/authorization
  resource:
    userInfoUri: https://api.linkedin.com/v1/people/~?format=json